defaults:
    - dataset: 2019/english
    - preprocessing: default
    - model: default
    - training: default

#resume: /home/linuxu/repos/ZeroSpeech/checkpoints/vq-vae/model.ckpt-12000.pt
resume: False
checkpoint_dir: /home/linuxu/repos/ZeroSpeech/checkpoints/
tensorboard_dir: /home/linuxu/repos/ZeroSpeech/logs/